<!-- DEBUGGER -->
<style>
    <?= file_get_contents($this->css_path); ?>
</style>

<div class="gdbg">
    <a href="" class="gdbg-toggler">Debugger ▲</a>
    <div class="gdbg-container">
        <div class="gdbg-menu">
            <a href="" data-target="#gdbg-tab-1">
                { if(count($this->messages) > 0) }
                <i>{{ count($this->messages) }}</i>
                { /if }
                Console
            </a>
            <a href="" data-target="#gdbg-tab-2">
                { if(count($this->exceptions) > 0) }
                <i>{{ count($this->exceptions) }}</i>
                { /if }
                Exceptions
            </a>
            <a href="" data-target="#gdbg-tab-3">Timeline</a>
            <a href="" data-target="#gdbg-tab-4">
                <span class="gdbg-status-code gdbg-status-code-{{ $this->method_type }}">{{ $this->request_method }}</span>
                Request
            </a>
            <a href="" data-target="#gdbg-tab-5">Headers</a>
            <a href="" data-target="#gdbg-tab-6">
                <span class="gdbg-status-code gdbg-status-code-{{ $this->status_type }}">{{ $this->status }}</span>
                Response
            </a>
            <a href="" data-target="#gdbg-tab-7">Session</a>
            <a href="" data-target="#gdbg-tab-8">Cookies</a>
            <a href="" data-target="#gdbg-tab-9">Application</a>
            <a href="" class="gdbg-close">✖️</a>
        </div>

        <div class="gdbg-content">
            <div class="gdbg-tab" id="gdbg-tab-1">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->messages as $message) }
                    <tr class="gdbg-row-{{ $message['type'] }}">
                        <td class="gdbg-message-time">
                            {{ $message['time'] }}
                        </td>
                        <td class="gdbg-message">
                            { if($message['type'] == 'error') }🚫{ /if }
                            { if($message['type'] == 'warning') }⚠️{ /if }
                            { if($message['type'] == 'dump') }
                            <span title="Total length: {{ strlen($message['text']) }}" class="gdbg-expandable-value">{{ $message['text'] }}</span>
                            { else }
                            {{ $message['text'] }}
                            { /if }
                        </td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-2">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->exceptions as $e) }
                    <tr class="gdbg-row-error">
                        <td class="gdbg-message-time">
                            {{ $e['time'] }}
                        </td>
                        <td class="gdbg-message">
                            🚫 <strong>{{ $e['exception']->getMessage() }}</strong> on file <strong>{{ $e['exception']->getFile() }}</strong> at line <strong>{{ $e['exception']->getLine() }}.</strong>
                            <br>
                            <a href="" class="gdbg-trace-toggle">See trace ▼</a>
                            <div class="gdbg-exception-trace">
                                {{!! nl2br($e['exception']->getTraceAsString()) !!}}
                            </div>
                        </td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-3">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->timers as $name => $value) }
                    <tr>
                        <td class="gdbg-data-key">
                            {{ $name }}
                        </td>
                        <td class="gdbg-timer-progress">
                            <div class="gdbg-timer-bar" style="--gdbg-bar-width: {{ $value['size'] }}">
                                {{ $value['duration_string'] }}
                            </div>
                        </td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-4">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->request as $key => $value) }
                    <tr>
                        <td class="gdbg-data-key">{{ $key }}</td>
                        <td class="gdbg-data-value">{{ $value }}</td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-5">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->headers as $key => $value) }
                    <tr>
                        <td class="gdbg-data-key">{{ $key }}</td>
                        <td class="gdbg-data-value">{{ $value }}</td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-6">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->response as $key => $value) }
                    <tr>
                        <td class="gdbg-data-key">{{ $key }}</td>
                        <td class="gdbg-data-value">{{ $value }}</td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-7">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->session as $key => $value) }
                    <tr>
                        <td class="gdbg-data-key">{{ $key }}</td>
                        <td class="gdbg-data-value">{{ json_encode($value) }}</td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-8">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->cookies as $key => $value) }
                    <tr>
                        <td class="gdbg-data-key">{{ $key }}</td>
                        <td class="gdbg-data-value">{{ json_encode($value) }}</td>
                    </tr>
                    { /foreach }
                </table>
            </div>

            <div class="gdbg-tab" id="gdbg-tab-9">
                <table cellspacing="0" cellpadding="0">
                    { foreach($this->application as $key => $value) }
                    <tr>
                        <td class="gdbg-data-key">{{ $key }}</td>
                        <td class="gdbg-data-value">{{ $value }}</td>
                    </tr>
                    { /foreach }
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    <?= file_get_contents($this->js_path); ?>
</script>
<!-- ./ END OF DEBUGGER -->